import { audi,
  acura,
  alfa_Romeo,
  aston_Martin,
  bentley,
  bmw,
  bugatti,
  buick,
  cadillac,
  chery,
  chevrolet,

  chrysler,
  citroen,
  dacia,
  daewoo,
  dodge,
  ferrari,
  fiat,
  ford,
  gaz,
  holden,
  honda,
  hyundai,

  infiniti,
  jaguar,
  jeep,
  kia,
  lada,
  lamborghini,
  lancia,
  land_rover,
  lexus,
  lotus,
  maserati,
  maybach,
  mazda,
  mercedes,
  mercury,
  mini,
  mitsubishi,
  nissan,
  opel,
  pagani,
  peugeot,
  pontiac,
  porshe,
  renault,
  rolls_royce,
  rover,
  saab,
  scion,
  seat,
  skoda,
  ssang_yong,
  subaru,
  suzuki,
  toyota,
  vauxhall,
  volkswagen,
  volvo,
} from '../../images';

const cars = [
  { stamp: audi,
    text: 'Ауди' },
  { stamp: acura,
    text: 'Акура' },
  { stamp: alfa_Romeo,
    text: 'Альфа-Ромео' },
  { stamp: aston_Martin,
    text: 'Астон Мартин' },
  { stamp: bentley,
    text: 'Бентли' },
  { stamp: bmw,
    text: 'БМВ' },
  { stamp: bugatti,
    text: 'Бугатти' },
  { stamp: buick,
    text: 'Бьюик' },
  { stamp: cadillac,
    text: 'Кадиллак' },
  { stamp: chery,
    text: 'Чери' },
  { stamp: chevrolet,
    text: 'Шевроле' },


  { stamp: chrysler,
    text: 'Крайслер' },
  { stamp: citroen,
    text: 'Ситроен' },
  { stamp: dacia,
    text: 'Дачия' },
  { stamp: daewoo,
    text: 'Део' },
  { stamp: dodge,
    text: 'Додж' },
  { stamp: ferrari,
    text: 'Феррари' },
  { stamp: fiat,
    text: 'Фиат' },
  { stamp: ford,
    text: 'Форд' },
  { stamp: gaz,
    text: 'ГАЗ' },
  { stamp: holden,
    text: 'Холден' },
  { stamp: honda,
    text: 'Хонда' },
  { stamp: hyundai,
    text: 'Хюндай' },
  { stamp: infiniti,
    text: 'Инфинити' },
  { stamp: jaguar,
    text: 'Ягуар' },
  { stamp: jeep,
    text: 'Джип' },
  { stamp: kia,
    text: 'КИЯ' },
  { stamp: lada,
    text: 'Лада' },
  { stamp: lamborghini,
    text: 'Ламборжини' },
  { stamp: lancia,
    text: 'Лянча' },
  { stamp: land_rover,
    text: 'Лэнд Ровер' },
  { stamp: lexus,
    text: 'Лексус' },
  { stamp: lotus,
    text: 'Лотус' },
  { stamp: maserati,
    text: 'Мазерати' },
  { stamp: maybach,
    text: 'Майбах' },
  { stamp: mazda,
    text: 'Мазда' },
  { stamp: mercedes,
    text: 'Мерседес' },
  { stamp: mercury,
    text: 'Меркури' },
  { stamp: mini,
    text: 'Мини' },
  { stamp: mitsubishi,
    text: 'Мицубиси' },
  { stamp: nissan,
    text: 'Ниссан' },
  { stamp: opel,
    text: 'Опель' },
  { stamp: pagani,
    text: 'Пагани' },
  { stamp: peugeot,
    text: 'Пежо' },
  { stamp: pontiac,
    text: 'Понтиак' },
  { stamp: porshe,
    text: 'Порш' },
  { stamp: renault,
    text: 'Рено' },
  { stamp: rolls_royce,
    text: 'Ролс Ройс' },
  { stamp: rover,
    text: 'Ровер' },
  { stamp: saab,
    text: 'Сааб' },
  { stamp: scion,
    text: 'Скион' },
  { stamp: seat,
    text: 'Сеат' },
  { stamp: skoda,
    text: 'Шкода' },
  { stamp: ssang_yong,
    text: 'Санг Ёнг' },
  { stamp: subaru,
    text: 'Субару' },
  { stamp: suzuki,
    text: 'Сузуки' },
  { stamp: toyota,
    text: 'Тайота' },
  { stamp: vauxhall,
    text: 'Воксхолл' },
  { stamp: volvo,
    text: 'Вольво' },
  { stamp: volkswagen,
    text: 'Фольксваген' },
];

export default cars;